name: 'buster'

on:
  push:
    paths:
      - 'run.sh'
      - '.github/workflows/buster.yml'
  repository_dispatch:
    types: [ ghdl ]

jobs:

  build:
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        backend: [ mcode, llvm-7, gcc-8.3.0 ]
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Clone ghdl
      run: git clone https://github.com/ghdl/ghdl

    - name: Build 'ghdl' and 'pkg' images
      run: ./run.sh -b
      env:
        TASK: buster+${{ matrix.backend }}

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}

    - name: Deploy to DockerHub
      run: ./run.sh ""

  trigger:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        ./.github/trigger.sh vunit
        ./.github/trigger.sh synth
      env:
        GHDL_BOT_TOKEN: ${{ secrets.GHDL_BOT }}
